### ISSUE TITLE
seek help, How can I solve this problem

### ISSUE THREAD

**Issue by 1hexf1** [wtliao/text2image#8]
Traceback (most recent call last):
  File "main.py", line 410, in <module>
    image_encoder = CNN_ENCODER(cfg.TEXT.EMBEDDING_DIM)
  File "/data01/hxf/text2image/DAMSM.py", line 127, in __init__
    model = models.inception_v3(pretrained=True, transform_input=False)
  File "/home/omnisky/hxf/lib/python3.6/site-packages/torchvision/models/inception.py", line 53, in inception_v3
    progress=progress)
  File "/home/omnisky/hxf/lib/python3.6/site-packages/torch/hub.py", line 557, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/omnisky/hxf/lib/python3.6/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/omnisky/hxf/lib/python3.6/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by wtliao** [comment]
@1hexf1 this problem is mainly caused by the python version. please refe to this [issue](https://github.com/CSAILVision/places365/issues/49). Please let me know if you could solve it. Thanks.

**Comment by 1hexf1** [comment]
Hello author, what is your Python version and PyTorch version?

**Comment by 1hexf1** [comment]
@wtliao Hello author, what is your Python version and PyTorch version?

**Comment by 1hexf1** [comment]
I have succeeded in solving the problem. InceptionV3 model loading problem.
 It needs to download the model and replace it manually.
Also, I upgraded Pytorch to use Pytorch1.7.

**Comment by wtliao** [comment]
@1hexf1 thanks  a lot for your report!
